// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MoneyManager.DataAccess;

namespace MoneyManager.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190821104527_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoneyManagerClassLibrary.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<string>("Name");

                    b.Property<int?>("UserForeignKey");

                    b.HasKey("AssetId");

                    b.HasIndex("UserForeignKey");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MoneyManagerClassLibrary.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int?>("AssetForeignKey");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.HasKey("TransactionId");

                    b.HasIndex("AssetForeignKey");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyManagerClassLibrary.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoneyManagerClassLibrary.Asset", b =>
                {
                    b.HasOne("MoneyManagerClassLibrary.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserForeignKey");
                });

            modelBuilder.Entity("MoneyManagerClassLibrary.Transaction", b =>
                {
                    b.HasOne("MoneyManagerClassLibrary.Asset", "Asset")
                        .WithMany("Transactions")
                        .HasForeignKey("AssetForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
