// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyManager.DataAccess;

namespace MoneyManager.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoneyManager.DataAccess.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<string>("Name");

                    b.Property<int?>("UserForeignKey");

                    b.HasKey("AssetId");

                    b.HasIndex("UserForeignKey");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MoneyManager.DataAccess.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsExpenses");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentCategoryCategoryId");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MoneyManager.DataAccess.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int?>("AssetForeignKey");

                    b.Property<int?>("CategoryForeignKey");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.HasKey("TransactionId");

                    b.HasIndex("AssetForeignKey");

                    b.HasIndex("CategoryForeignKey");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyManager.DataAccess.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoneyManager.DataAccess.Models.Asset", b =>
                {
                    b.HasOne("MoneyManager.DataAccess.Models.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserForeignKey");
                });

            modelBuilder.Entity("MoneyManager.DataAccess.Models.Category", b =>
                {
                    b.HasOne("MoneyManager.DataAccess.Models.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryCategoryId");
                });

            modelBuilder.Entity("MoneyManager.DataAccess.Models.Transaction", b =>
                {
                    b.HasOne("MoneyManager.DataAccess.Models.Asset", "Asset")
                        .WithMany("Transactions")
                        .HasForeignKey("AssetForeignKey");

                    b.HasOne("MoneyManager.DataAccess.Models.Category", "Category")
                        .WithMany("TransactionList")
                        .HasForeignKey("CategoryForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
